name: Hello-Work-Docker-Workflow
on: 
  push: 
    branches: [main]
    paths: [ hello-world-docker-action/** ]
  
  workflow_dispatch:
    inputs:
      who-to-greet:
        default: 'World'


jobs:
  Run-local-action:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: ${{github.triggering_actor}}

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
    
